#ifndef OMAACS_GEOMETRY_TRANSFORMATION_H
#define OMAACS_GEOMETRY_TRANSFORMATION_H

#include "../../libs/OMAACS_NUM/OMAACS_NUM/src/vector.h"
#include "../../libs/OMAACS_NUM/OMAACS_NUM/src/matrix.h"


#endif#ifndef OMAACS_GEOMETRY_TRANSFORMATION_H
#define OMAACS_GEOMETRY_TRANSFORMATION_H



#endif